services:
  db:
    image: postgres:16
    container_name: myrun-postgres
    environment:
      POSTGRES_USER: myrun
      POSTGRES_PASSWORD: myrun
      POSTGRES_DB: myrun_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
    container_name: myrun-api
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: myrun
      POSTGRES_PASSWORD: myrun
      RAILS_ENV: development
    depends_on:
      - db

volumes:
  pgdata:
